# Generated by Django 5.1.2 on 2024-10-24 08:16

import MyPlantApp.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[MyPlantApp.profiles.validators.capital_letter_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[MyPlantApp.profiles.validators.capital_letter_validator], verbose_name='Last Name'),
        ),
    ]
