# Generated by Django 5.1.2 on 2024-10-20 12:03

import TastyRecipesApp.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(error_messages={'unique': 'This nickname is already taken.'}, max_length=20, unique=True, validators=[TastyRecipesApp.core.validators.validate_nickname_length])),
                ('first_name', models.CharField(max_length=30, validators=[TastyRecipesApp.core.validators.validate_name_capitalized])),
                ('last_name', models.CharField(max_length=30, validators=[TastyRecipesApp.core.validators.validate_name_capitalized])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
