# Generated by Django 5.1.2 on 2024-10-24 06:39

import MyPlantApp.plants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('OP', 'Outdoor Plants'), ('IP', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[MyPlantApp.plants.validators.only_letters_validator])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
